return {
  -- Snippets
  -- {
  --   "L3MON4D3/LuaSnip",
  --   version = "2.*",
  --   build = "make install_jsregexp",
  --   dependencies = { "rafamadriz/friendly-snippets" },
  --   config = function()
  --     require("luasnip.loaders.from_snipmate").lazy_load()
  --     require("luasnip.loaders.from_vscode").lazy_load()
  --
  --     vim.api.nvim_create_autocmd("ModeChanged", {
  --       group = vim.api.nvim_create_augroup("clear-snippets-on-mode-change", { clear = true }),
  --       pattern = { "s:n", "i:*" },
  --       callback = function(args)
  --         local luasnip = require("luasnip")
  --         if luasnip.session.current_nodes[args.buf] and not luasnip.session.jump_active then
  --           luasnip.unlink_current()
  --         end
  --       end,
  --     })
  --   end,
  -- },
}
